### ISSUE TITLE
kube-janitor leaves behind replicaset relics

### ISSUE THREAD

**Issue by CookieComputing** [hjacobs/kube-janitor#11]
`kube-janitor` will leave behind an old replicaset when you edit the deployment for `kube-janitor`

Steps to reproduce:
- `kubectl apply -f deploy/`
- `kubectl edit deploy kube-janitor`
- (some edit of the deployment)
- `kubectl get replicasets`

**Comment by CookieComputing** [comment]
@hjacobs

**Comment by hjacobs** [comment]
@CookieComputing can you elaborate, e.g. by showing the output of above commands?

**Comment by devkid** [comment]
This is the normal behavior of a `Deployment`: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#deploymentspec-v1-apps (see `revisionHistoryLimit`).

**Comment by hjacobs** [comment]
@devkid that was my assumption, too.
