### ISSUE TITLE
Provide special value for janitor/ttl that will block wipe process. 

### ISSUE THREAD

**Issue by antban** [hjacobs/kube-janitor#38]
Sometimes people use the same file to deploy to different environments (live, staging, pr), as deployments to different stacks may differ only in parameter values (and parameters are taken from config maps or some other template engine).
Unfortunately, presence of janitor/ttl forces people to create several yaml files with only difference - presence of janitor/ttl annotation.
I believe that ability to set special value (janitor/ttl: **undead**, for example) that is blocking janitor in specific environments will allow people to create unified deployments.

**Comment by hjacobs** [comment]
I'm confused by your "undead" example, do you mean something like "TTL: forever"?

**Comment by antban** [comment]
@hjacobs yes, forever also works, but it's much less fun. 
If you agree with this feature, I can make PR

**Comment by hjacobs** [comment]
@antban yes, a PR would be welcome :smile:
