### ISSUE TITLE
Support `deployment-time` annotation

### ISSUE THREAD

**Issue by aermakov-zalando** [hjacobs/kube-janitor#43]
This annotation is injected during deployment time, so the janitor should prefer using it instead of `creationTime`. Currently it'll remove a deployment 2 days after it was created even if the users redeploy every hour, which is definitely not what anyone would expect.

**Comment by jasonmorganson** [comment]
Does [this](https://github.com/hjacobs/kube-janitor/pull/33) do it?

**Comment by hjacobs** [comment]
@jasonmorganson the linked PR #33 is an alternative version to track "last update time" without requiring a specific annotation injected by some other tool (like CI/CD pipeline).

**Comment by hjacobs** [comment]
This was implemented and released in https://github.com/hjacobs/kube-janitor/releases/tag/20.2.0
