### ISSUE TITLE
Publishing through helm charts repo?

### ISSUE THREAD

**Issue by mayppong** [hjacobs/kube-janitor#44]
Hi there,
Would you be into the idea of putting `kube-janitor` up on helm charts repo? I'm happy to put it up for you as well, if you're OK with it.

EDIT: There is already another package using the name `kube-janitor` so this package will have to be published under another name though. (https://github.com/helm/charts/blob/master/incubator/kube-janitor/Chart.yaml)

**Comment by mayppong** [comment]
Just `janitor`?

**Comment by hjacobs** [comment]
@mayppong SGTM

**Comment by mayppong** [comment]
Here is my current working branch for this. I've got it mostly working and installing through helms. Just need to do a write up of the README file and I should be ready to submit this to the helm/charts repo. Please let me know if there's anything you'd like to add/change.
https://github.com/mayppong/charts/tree/add-hjacobs-kube-janitor-chart/incubator/janitor

**Comment by mayppong** [comment]
Here is the PR I created for the helm chart repo for reference
https://github.com/helm/charts/pull/18119

**Comment by mayppong** [comment]
So it looks like they want everyone to host their own chart now which apparently can be done through GitHub Pages. Are you open to doing that for me?
https://github.com/helm/hub/blob/master/docs/github.md

**Comment by mayppong** [comment]
This seems to be working fine. Just need to add some notes to README file to let people know that this is possible. I will put something up when I'm done my work day.
